name: Comment on PR with Benchmarks

on:
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        pip install asv asv-runner  # PR TODO: move to pyprojct.toml

    - name: Run ASV benchmarks
      run: asv run

    - name: Compare PR against main
      run: |
        git remote add upstream https://github.com/${{ github.repository }}.git
        git fetch upstream
        asv continuous upstream/main HEAD --verbose || true
        asv compare upstream/main HEAD --sort ratio --verbose | tee output

    - name: Post benchmark results as PR comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        header: "Benchmark Results"
        path: output
