name: Publish the documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements-doc.txt
      - name: Build documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: mike deploy --push --update-aliases ${{ steps.git.outputs.tag }} latest
      - name: Determine version tag
        id: get-tag
        run: |
          if [ -n "${{ github.event.ref_type }}" ] && [ "${{ github.event.ref_type }}" == "tag" ]; then
            echo "version_tag=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "alias=stable" >> $GITHUB_ENV
          else
            echo "version_tag=latest" >> $GITHUB_ENV
            echo "alias=main" >> $GITHUB_ENV
      - name: Build documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: mike deploy --push --update-aliases ${{ env.version_tag }} ${{ env.alias }}
