name: Publish the documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements-doc.txt
      - name: Set up Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Get latest tag or commit SHA
        id: git
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "no-tags")
          if [ "$TAG" = "no-tags" ]; then
            TAG="main"
          fi
          echo "::set-output name=tag::$TAG"
      - name: Build documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mike deploy --update-aliases --push --branch ${{ steps.git.outputs.tag }} unstable
          mike set-default --push --force unstable
