name: Publish the documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements-doc.txt
      - name: Set up Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Build documentation
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "main")
          TAG_EXISTS=$(git describe --tags --exact-match 2>/dev/null && echo "true" || echo "false")
          if [ "$TAG_EXISTS" = "true" ]; then
            mike deploy --update-aliases --push --branch $TAG stable
            mike set-default stable
          else
            mike deploy --update-aliases --push --branch main unstable
          fi
